-- Run this in Supabase SQL Editor before creating the Database Webhook.
-- Keep the bucket private. n8n should use a service-role credential server-side.

create table if not exists public.documents (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  file_path text not null,
  file_url text not null,
  document_type text not null default 'other' check (document_type in ('aadhaar', 'pan', 'passport', 'marksheet', 'bank_statement', 'other')),
  original_filename text not null,
  mime_type text not null,
  file_size integer not null check (file_size > 0),
  status text not null default 'processing' check (status in ('processing', 'verified', 'needs_review', 'likely_forged')),
  confidence_score integer not null default 0 check (confidence_score between 0 and 100),
  checks jsonb not null default '[]'::jsonb,
  report jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.documents enable row level security;

create policy "users can read their own documents"
  on public.documents for select to authenticated
  using (auth.uid() = user_id);

create policy "users can create their own documents"
  on public.documents for insert to authenticated
  with check (auth.uid() = user_id);

insert into storage.buckets (id, name, public)
values ('documents', 'documents', false)
on conflict (id) do nothing;

create policy "users can upload their own documents"
  on storage.objects for insert to authenticated
  with check (bucket_id = 'documents' and (storage.foldername(name))[1] = auth.uid()::text);

create policy "users can read their own documents"
  on storage.objects for select to authenticated
  using (bucket_id = 'documents' and (storage.foldername(name))[1] = auth.uid()::text);

alter publication supabase_realtime add table public.documents;

-- In the Supabase dashboard use Database > Webhooks > Create webhook:
-- Name: documents_insert_to_n8n
-- Table: public.documents, Events: INSERT, Method: POST
-- URL: n8n Webhook node's Production URL
-- Headers: Content-Type: application/json
-- Do not put the n8n URL or tokens in this SQL file.