import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Switch } from "@/components/ui/switch";
import { getInitials } from "@/lib/veriscan";
import { Bell, Check, Copy, KeyRound, LockKeyhole, RefreshCw, ShieldCheck, UserRound } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

export default function Settings() {
  const { user } = useAuth();
  const [emailAlerts, setEmailAlerts] = useState(true);
  const [reviewAlerts, setReviewAlerts] = useState(true);
  const [apiKey, setApiKey] = useState("");

  const generateKey = () => {
    const generated = `vs_live_${crypto.randomUUID().replaceAll("-", "").slice(0, 24)}`;
    setApiKey(generated);
    toast.success("API key generated", { description: "Copy it now. For security, this preview does not persist secret values." });
  };

  return <div className="mx-auto max-w-[1100px]"><div className="border-b border-border pb-7"><p className="eyebrow text-bronze-dark">Workspace controls</p><h1 className="mt-3 font-serif text-3xl font-bold tracking-[-0.035em] sm:text-4xl">Settings</h1><p className="mt-2 text-sm leading-6 text-muted-ink">Manage your account, integration access, and alert preferences.</p></div><div className="mt-7 space-y-7"><section className="rounded-[20px] border border-border bg-paper p-5 sm:p-7"><div className="flex items-start gap-4"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-bronze/12 text-bronze-dark"><UserRound className="h-5 w-5" /></div><div><p className="eyebrow text-bronze-dark">Account details</p><h2 className="mt-2 font-serif text-2xl font-bold">Your VeriScan identity</h2><p className="mt-2 text-sm leading-6 text-muted-ink">These details are supplied by your authenticated account foundation.</p></div></div><div className="mt-7 grid gap-5 sm:grid-cols-2"><div><label className="mb-2 block text-xs font-semibold uppercase tracking-[0.11em] text-muted-ink">Full name</label><Input value={user?.name ?? "Account holder"} readOnly className="h-11 border-border bg-paper-deep text-ink" /></div><div><label className="mb-2 block text-xs font-semibold uppercase tracking-[0.11em] text-muted-ink">Email address</label><Input value={user?.email ?? "Authenticated account"} readOnly className="h-11 border-border bg-paper-deep text-ink" /></div></div><div className="mt-5 flex items-center gap-3 rounded-xl border border-border bg-paper-deep p-4"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-charcoal text-sm font-semibold text-paper">{getInitials(user?.name)}</span><div><p className="text-sm font-semibold">Authenticated workspace</p><p className="mt-1 text-xs text-muted-ink">User-specific scan data is protected by server-side access checks.</p></div></div></section>
    <section className="rounded-[20px] border border-border bg-paper p-5 sm:p-7"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div className="flex items-start gap-4"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-bronze/12 text-bronze-dark"><KeyRound className="h-5 w-5" /></div><div><p className="eyebrow text-bronze-dark">Organization API</p><h2 className="mt-2 font-serif text-2xl font-bold">Connect VeriScan to onboarding</h2><p className="mt-2 max-w-xl text-sm leading-6 text-muted-ink">Generate an access key for an internal integration. Keep it in your secrets manager and rotate it when a team member leaves.</p></div></div><Button variant="outline" className="border-border bg-transparent text-ink hover:bg-paper-deep" onClick={generateKey}><RefreshCw className="mr-2 h-4 w-4" /> Generate key</Button></div>{apiKey && <div className="mt-6 flex flex-col gap-3 rounded-xl border border-bronze/25 bg-bronze/6 p-4 sm:flex-row sm:items-center sm:justify-between"><code className="break-all text-xs text-ink">{apiKey}</code><Button variant="outline" size="sm" className="self-start border-bronze/30 bg-transparent text-ink hover:bg-bronze/10 sm:self-auto" onClick={() => navigator.clipboard?.writeText(apiKey).then(() => toast.success("API key copied"))}><Copy className="mr-2 h-3.5 w-3.5" /> Copy</Button></div>}<div className="mt-6 flex items-center gap-3 rounded-xl border border-border bg-paper-deep p-4 text-xs leading-5 text-muted-ink"><LockKeyhole className="h-4 w-4 shrink-0 text-bronze-dark" /> In the production integration, only a one-way hash of API keys is retained in the database.</div></section>
    <section className="rounded-[20px] border border-border bg-paper p-5 sm:p-7"><div className="flex items-start gap-4"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-bronze/12 text-bronze-dark"><Bell className="h-5 w-5" /></div><div><p className="eyebrow text-bronze-dark">Notifications</p><h2 className="mt-2 font-serif text-2xl font-bold">Choose what reaches you</h2></div></div><div className="mt-7 divide-y divide-border"><Preference label="Report ready" detail="Receive an email when a screening has finished." checked={emailAlerts} onCheckedChange={setEmailAlerts} /><Preference label="Human review updates" detail="Be notified when a requested review changes status." checked={reviewAlerts} onCheckedChange={setReviewAlerts} /></div></section>
    <section className="rounded-[20px] border border-border bg-charcoal p-5 text-paper sm:p-7"><div className="flex items-start gap-4"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-bronze text-ink"><ShieldCheck className="h-5 w-5" /></div><div><p className="eyebrow text-bronze-light">Privacy controls</p><h2 className="mt-2 font-serif text-2xl font-bold">Keep the data boundary clear</h2><p className="mt-2 max-w-xl text-sm leading-6 text-paper/60">Uploaded files are stored through a secure reference path. Reports are designed to remain useful without making raw document bytes part of application records.</p><div className="mt-6 flex items-center gap-2 text-sm font-semibold text-bronze-light"><Check className="h-4 w-4" /> No government database lookup</div></div></div></section></div></div>;
}

function Preference({ label, detail, checked, onCheckedChange }: { label: string; detail: string; checked: boolean; onCheckedChange: (checked: boolean) => void }) { return <div className="flex items-center justify-between gap-5 py-4"><div><p className="text-sm font-semibold">{label}</p><p className="mt-1 text-sm leading-6 text-muted-ink">{detail}</p></div><Switch checked={checked} onCheckedChange={onCheckedChange} aria-label={label} /></div>; }
